name = "blog-auth-worker"
main = "src/index.ts"
compatibility_date = "2024-12-18"

# 기본 환경변수 (로컬 개발용)
[vars]
GITHUB_CLIENT_ID = "Ov23liRliHgRtY9KfVny"
GITHUB_CLIENT_SECRET = "6c0564608549ccba2bf2db5b4eb055da7055860e"
JWT_SECRET = "mK8N2vP9xQ7wE5rT3uI6oL1sA4dF8gH2jK5nM9pR7tY0zX3cV6bN1mQ4wE7rT9uI2oP5sL8dF1gH4jK7nM0pR3tY6"
ALLOWED_ORIGINS = "http://localhost:3000,http://127.0.0.1:8787"

[[kv_namespaces]]
binding = "AUTH_SESSIONS"
id = "c600a7ac15c3439c9c1712e54aaa1ff9"
preview_id = "c600a7ac15c3439c9c1712e54aaa1ff9"

# 로컬 개발 환경 설정
[env.development]
name = "blog-auth-worker-dev"
GITHUB_CLIENT_ID = "Ov23liRliHgRtY9KfVny"
GITHUB_CLIENT_SECRET = "6c0564608549ccba2bf2db5b4eb055da7055860e"
JWT_SECRET = "mK8N2vP9xQ7wE5rT3uI6oL1sA4dF8gH2jK5nM9pR7tY0zX3cV6bN1mQ4wE7rT9uI2oP5sL8dF1gH4jK7nM0pR3tY6"
ALLOWED_ORIGINS = "http://localhost:3000,http://127.0.0.1:8787"

[[env.development.kv_namespaces]]
binding = "AUTH_SESSIONS"
id = "c600a7ac15c3439c9c1712e54aaa1ff9"
preview_id = "c600a7ac15c3439c9c1712e54aaa1ff9"

[env.production]
name = "blog-auth-worker"
GITHUB_CLIENT_ID = "Ov23liRliHgRtY9KfVny"
GITHUB_CLIENT_SECRET = "6c0564608549ccba2bf2db5b4eb055da7055860e"
JWT_SECRET = "mK8N2vP9xQ7wE5rT3uI6oL1sA4dF8gH2jK5nM9pR7tY0zX3cV6bN1mQ4wE7rT9uI2oP5sL8dF1gH4jK7nM0pR3tY6"
ALLOWED_ORIGINS = "https://jook1356.github.io,http://localhost:3000"

[[env.production.kv_namespaces]]
binding = "AUTH_SESSIONS"
id = "c600a7ac15c3439c9c1712e54aaa1ff9"
preview_id = "c600a7ac15c3439c9c1712e54aaa1ff9"

